config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get 'users', to: 'devise/sessions#new'
    get 'users/password', to: 'devise/passwords#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users
  #root to: 'home#index'
  get 'home/about'
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: {minimum:5, maximum: 10, too_long: "%{count} characters is the maximum allowed", too_short: "%{count} characters is the minimum allowed"}
  validates :description, presence: true, length: {minimum:10, maximum: 500, too_long: "%{count} characters is the maximum allowed", too_short: "%{count} characters is the minimum allowed"}
  validates :keywords, presence: true, length: {minimum:2, maximum: 10, too_long: "%{count} characters is the maximum allowed", too_short: "%{count} characters is the minimum allowed"}
  has_many_attached :images

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :keywords, images:[])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/about.html.erb
<h1>this is about page </h1>
<p>you can write any info  about the company </p>

app/views/layouts/_footer.html.erb
<div class=" my-5">
  <footer class="text-center text-lg-start text-white" style="background-color: #45526e">
    <div class="container-fluid p-4 pb-0">
      <section class="">
        <div class="row">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">
              Company name
            </h6>
            <p>
              Here you can use rows and columns to organize your footer
              content. Lorem ipsum dolor sit amet, consectetur adipisicing
              elit.
            </p>
          </div>
          <!-- Grid column -->

          <hr class="w-100 clearfix d-md-none" />

          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">Products</h6>
            <p>
              <a class="text-white">MDBootstrap</a>
            </p>
            <p>
              <a class="text-white">MDWordPress</a>
            </p>
            <p>
              <a class="text-white">BrandFlow</a>
            </p>
            <p>
              <a class="text-white">Bootstrap Angular</a>
            </p>
          </div>
          <!-- Grid column -->

          <hr class="w-100 clearfix d-md-none" />

          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">
              Useful links
            </h6>
            <p>
              <a class="text-white">Your Account</a>
            </p>
            <p>
              <a class="text-white">Become an Affiliate</a>
            </p>
            <p>
              <a class="text-white">Shipping Rates</a>
            </p>
            <p>
              <a class="text-white">Help</a>
            </p>
          </div>

          <!-- Grid column -->
          <hr class="w-100 clearfix d-md-none" />

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
            <p><i class="fas fa-home mr-3"></i> New York, NY 10012, US</p>
            <p><i class="fas fa-envelope mr-3"></i> info@gmail.com</p>
            <p><i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
            <p><i class="fas fa-print mr-3"></i> + 01 234 567 89</p>
          </div>
          <!-- Grid column -->
        </div>
        <!--Grid row-->
      </section>
      <!-- Section: Links -->

      <hr class="my-3">

      <!-- Section: Copyright -->
      <section class="p-3 pt-0">
        <div class="row d-flex align-items-center">
          <!-- Grid column -->
          <div class="col-md-7 col-lg-8 text-center text-md-start">
            <!-- Copyright -->
            <div class="p-3">
              © 2020 Copyright:
              <a class="text-white" href="https://mdbootstrap.com/"
              >MDBootstrap.com</a
              >
            </div>
            <!-- Copyright -->
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-5 col-lg-4 ml-lg-0 text-center text-md-end">
            <!-- Facebook -->
            <a
              class="btn btn-outline-light btn-floating m-1"
              class="text-white"
              role="button"
            ><i class="fab fa-facebook-f"></i
            ></a>

            <!-- Twitter -->
            <a
              class="btn btn-outline-light btn-floating m-1"
              class="text-white"
              role="button"
            ><i class="fab fa-twitter"></i
            ></a>

            <!-- Google -->
            <a
              class="btn btn-outline-light btn-floating m-1"
              class="text-white"
              role="button"
            ><i class="fab fa-google"></i
            ></a>

            <!-- Instagram -->
            <a
              class="btn btn-outline-light btn-floating m-1"
              class="text-white"
              role="button"
            ><i class="fab fa-instagram"></i
            ></a>
          </div>
          <!-- Grid column -->
        </div>
      </section>
      <!-- Section: Copyright -->
    </div>
    <!-- Grid container -->
  </footer>
  <!-- Footer -->
</div>
<!-- End of .container -->

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Home', root_path , class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Upload Post', new_post_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class:"nav-link active" %>
        </li>
        <% if user_signed_in?  %>
          <li class="nav-item">
            <%= link_to 'Sing Out', destroy_user_session_path, class:"nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Account", edit_user_password_path, class: 'nav-link' %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to 'Sing Up', new_user_registration_path, class:"nav-link active" %>
          </li>
        <% end %>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagramclone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>

    <%= render 'layouts/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

  </body>
</html>

app/views/posts/_form.html.erb
<div>
  <%= form_with(model: post) do |form| %>
    <div>
      <% invalid = post.errors.include?(:title) %>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title, class: "form-control" %>
      <% if invalid %>
        <p style="color:red"><%= post.errors.full_messages_for(:title).join(",") %></p>
      <% end %>
    </div>

    <div>
      <% invalid = post.errors.include?(:description) %>
      <%= form.label :description, style: "display: block" %>
      <%= form.text_field :description, class:"form-control" %>
      <% if invalid %>
       <p style="color:red"><%= post.errors.full_messages_for(:description).join(",") %></p>
      <% end %>
    </div>

    <div>
      <% invalid = post.errors.include?(:keywords) %>
      <%= form.label :keywords, style: "display: block" %>
      <%= form.text_field :keywords, class: "form-control" %>
      <% if invalid  %>
       <p style="color:red"><%= post.errors.full_messages_for(:keywords).join(",") %></p>
      <% end %>
    </div>

    <div class="py-4">
      <%= form.file_field :images, multiple: true %>
    </div>

    <div>
      <%= form.submit class: 'btn btn-primary col-sm-12 col-12' %>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="post-container">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= post.description %>
  </p>

  <p>
    <strong>Keywords:</strong>
    <%= post.keywords %>
  </p>

  <p>
    <%#= link_to "Show this post", post %>
    <%= link_to "", post, class:"post-link" %>
  </p>
  <p>
    <% post.images.each do |image| %>
      <%= image_tag(image, style: "object-fit: contain")  %>
    <% end %>
  </p>
</div>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-xl-4 col-lg-6,col-md-8, col-10 mt-8" style="margin: auto" >
    <h1 style="margin-top: 20px">Editing post</h1>
    <%= render "form", post: @post %>
  </div>
</div>
<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<%= stylesheet_link_tag("post") %>
<p style="color: green"><%= notice %></p>

<div class="text-center">
  <h1>All Posts</h1>
  <div id="posts">
    <% @posts.each do |post| %>
      <%= render post %>
<!--      <p>-->
        <%#= link_to "Show this post", post %>
<!--      </p>-->
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-xl-4 col-lg-6,col-md-8, col-10" style="margin: auto">
   <h1 style="padding-top: 20px">New post</h1>
   <%= render "form", post: @post %> <br>
    <div>
      <%= link_to "Back to posts", posts_path %>
    </div>
  </div>


</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>